PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE Team (TeamId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, TeamName VARCHAR(30) NOT NULL UNIQUE, Venue VARCHAR(40) NOT NULL, Wins INTEGER NULL, Losses INTEGER NULL);
INSERT INTO Team VALUES(1,'Toronto Raptors','Scotiabank Arena',56,26);
INSERT INTO Team VALUES(2,'Golden State Warriors','Chase Center',57,25);
INSERT INTO Team VALUES(3,'Phoenix Suns','Talking Stick Resort Arena',19,63);
INSERT INTO Team VALUES(4,'Houston Rockets','Toyota Center',53,29);
INSERT INTO Team VALUES(5,'New York Knicks','Madison Square Garden',17,65);
INSERT INTO Team VALUES(6,'Detroit Pistons','Little Caesars Arena',41,41);
INSERT INTO Team VALUES(7,'Atlanta Hawks','State Farm Arena',29,53);
INSERT INTO Team VALUES(8,'Boston Celtics','TD Garden',49,33);
INSERT INTO Team VALUES(9,'Los Angeles Lakers','Staples Center',37,45);
INSERT INTO Team VALUES(10,'Chicago Bulls','United Center',22,60);
INSERT INTO Team VALUES(11,'Brooklyn Nets','Barclays Center',42,40);
INSERT INTO Team VALUES(12,'Philadelphia 76ers','Wells Fargo Center',51,31);
INSERT INTO Team VALUES(13,'Cleveland Cavaliers','Rocket Mortgage FieldHouse',19,63);
INSERT INTO Team VALUES(14,'Indiana Pacers','Bankers Life Fieldhouse',48,34);
INSERT INTO Team VALUES(15,'Milwaukee Bucks','Fiserv Forum',60,22);
INSERT INTO Team VALUES(16,'Charlotte Hornets','Spectrum Center',39,43);
INSERT INTO Team VALUES(17,'Miami Heat','American Airlines Arena',39,43);
INSERT INTO Team VALUES(18,'Orlando Magic','Amway Center',42,40);
INSERT INTO Team VALUES(19,'Washington Wizards','Capital One Arena',32,50);
INSERT INTO Team VALUES(20,'Denver Nuggets','Pepsi Center',54,28);
INSERT INTO Team VALUES(21,'Minnesota Timberwolves','Target Center',36,46);
INSERT INTO Team VALUES(22,'Oklahoma City Thunder','Chesapeake Energy Arena',49,33);
INSERT INTO Team VALUES(23,'Portland Trail Blazers','Moda Center',53,29);
INSERT INTO Team VALUES(24,'Utah Jazz','Vivint Smart Home Arena',50,32);
INSERT INTO Team VALUES(25,'Los Angeles Clippers','Staples Center',48,34);
INSERT INTO Team VALUES(26,'Sacramento Kings','Golden 1 Center',39,43);
INSERT INTO Team VALUES(27,'Dallas Mavericks','American Airlines Center',33,49);
INSERT INTO Team VALUES(28,'Memphis Grizzlies','FedExForum',33,49);
INSERT INTO Team VALUES(29,'New Orleans Pelicans','Smoothie King Center',33,49);
INSERT INTO Team VALUES(30,'San Antonio Spurs','AT&T Center',48,34);
CREATE TABLE Player (PlayerId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, PlayerName VARCHAR(30) NOT NULL, Position VARCHAR(3) NOT NULL, Hometown VARCHAR(20) NOT NULL, GamesPlayed INTEGER NULL);
INSERT INTO Player VALUES(1,'Pascal Siakam','PF','Cameroon',82);
INSERT INTO Player VALUES(2,'Steph Curry','PG','Ohio',81);
INSERT INTO Player VALUES(3,'Devin Booker','SG','Michigan',43);
INSERT INTO Player VALUES(4,'James Harden','PG','Los Angeles',82);
INSERT INTO Player VALUES(5,'RJ Barret','SG','Mississauga',80);
INSERT INTO Player VALUES(6,'Andre Drummond','C','New York',82);
INSERT INTO Player VALUES(7,'John Collins','SF','Utah',80);
INSERT INTO Player VALUES(8,'Gordon Hayward','SG','Indiana',82);
INSERT INTO Player VALUES(9,'LeBron James','SF','Ohio',82);
INSERT INTO Player VALUES(10,'Zach LaVine','SG','Washington',81);
INSERT INTO Player VALUES(11,'Kyrie Irving','PG','Australia',69);
INSERT INTO Player VALUES(12,'Ben Simmons','PG','Australia',77);
INSERT INTO Player VALUES(13,'Tristan Thompson','PF','Brampton',79);
INSERT INTO Player VALUES(14,'Victor Oladipo','SG','Maryland',12);
INSERT INTO Player VALUES(15,'Brook Lopez','C','Los Angeles',82);
INSERT INTO Player VALUES(16,'Terry Rozier','PG','Ohio',82);
INSERT INTO Player VALUES(17,'Jimmy Butler','SG','Los Angeles',81);
INSERT INTO Player VALUES(18,'Aaron Gordon','SF','San Jose',80);
INSERT INTO Player VALUES(19,'Bradley Beal','SG','Missouri',80);
INSERT INTO Player VALUES(20,'Nikola Jokic','C','Serbia',82);
INSERT INTO Player VALUES(21,'Andrew Wiggins','SF','Toronto',71);
INSERT INTO Player VALUES(22,'Steven Adams','C','New Zealand',72);
INSERT INTO Player VALUES(23,'Damian Lillard','PG','Utah',75);
INSERT INTO Player VALUES(24,'Donovan Mitchell','PG','New York',82);
INSERT INTO Player VALUES(25,'Paul George','SF','Palmdale',53);
INSERT INTO Player VALUES(26,'Bogdan Bogdanovic','SF','Serbia',78);
INSERT INTO Player VALUES(27,'Luka Doncic','PG','Slovenia',80);
INSERT INTO Player VALUES(28,'Ja Morant','PG','South Carolina',81);
INSERT INTO Player VALUES(29,'Zion Williamson','PF','North Carolina',5);
INSERT INTO Player VALUES(30,'Rudy Gay','SF','Baltimore',72);
INSERT INTO Player VALUES(31,'Kelly Oubre Jr','SF','Louisiana',62);
INSERT INTO Player VALUES(33,'Russell Westbrook','PG','California',82);
CREATE TABLE Manager (ManagerId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, ManagerName VARCHAR(30) NOT NULL UNIQUE, College VARCHAR(30) NOT NULL, Experience INTEGER NULL);
INSERT INTO Manager VALUES(1,'Bobby Webster','California',2);
INSERT INTO Manager VALUES(2,'Bob Myers','UCLA',7);
INSERT INTO Manager VALUES(3,'James Jones','Miami',1);
INSERT INTO Manager VALUES(4,'Daryl Morey','Northwestern',12);
INSERT INTO Manager VALUES(5,'Steve Mills','Princeton',6);
INSERT INTO Manager VALUES(6,'Ed Stefanski','Pennsylvania',1);
INSERT INTO Manager VALUES(7,'Travis Schlenk','Bethel College',2);
INSERT INTO Manager VALUES(8,'Danny Ainge','Brigham Young',16);
INSERT INTO Manager VALUES(9,'Rob Pelinka','Michigan',2);
INSERT INTO Manager VALUES(10,'Gar Forman','Utah State',10);
CREATE TABLE Coach (CoachId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, CoachName VARCHAR(30) NOT NULL UNIQUE, StartDate DATE NOT NULL, Experience INTEGER NULL);
INSERT INTO Coach VALUES(1,'Nick Nurse','2018-06-14',1);
INSERT INTO Coach VALUES(2,'Steve Kerr','2014-05-19',5);
INSERT INTO Coach VALUES(3,'Monty Williams','2019-05-03',14);
INSERT INTO Coach VALUES(4,'Mike DAntoni','2016-06-01',29);
INSERT INTO Coach VALUES(5,'David Fizdale','2018-05-07',15);
INSERT INTO Coach VALUES(6,'Dwane Casey','2018-06-11',25);
INSERT INTO Coach VALUES(7,'Lloyd Pierce','2018-05-11',6);
INSERT INTO Coach VALUES(8,'Brad Stevens','2013-07-03',18);
INSERT INTO Coach VALUES(9,'Frank Vogel','2019-05-13',8);
INSERT INTO Coach VALUES(10,'Jim Boylen','2018-12-03',6);
CREATE TABLE Statistics (StatsId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Assists INTEGER NULL, Points INTEGER NULL, Steals INTEGER NULL, Turnovers INTEGER NULL);
INSERT INTO Statistics VALUES(1,12,34,3,7);
INSERT INTO Statistics VALUES(2,NULL,NULL,5,NULL);
INSERT INTO Statistics VALUES(3,32,98,61,17);
INSERT INTO Statistics VALUES(4,NULL,NULL,NULL,3);
INSERT INTO Statistics VALUES(5,NULL,NULL,NULL,NULL);
INSERT INTO Statistics VALUES(6,NULL,NULL,NULL,NULL);
INSERT INTO Statistics VALUES(7,NULL,NULL,NULL,NULL);
INSERT INTO Statistics VALUES(8,NULL,NULL,NULL,NULL);
INSERT INTO Statistics VALUES(9,NULL,NULL,NULL,23);
INSERT INTO Statistics VALUES(10,NULL,NULL,NULL,NULL);
CREATE TABLE Manage (TeamId VARCHAR(30) REFERENCES Team(TeamId), ManagerId INTEGER REFERENCES Manager(ManagerId));
CREATE TABLE Recruit (CoachId INTEGER REFERENCES Coach(CoachId), TeamId VARCHAR(30) REFERENCES Team(TeamId));
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('Team',30);
INSERT INTO sqlite_sequence VALUES('Player',33);
INSERT INTO sqlite_sequence VALUES('Manager',10);
INSERT INTO sqlite_sequence VALUES('Coach',10);
INSERT INTO sqlite_sequence VALUES('Statistics',10);
COMMIT;
